---
title: "Python Project - TFDS"
author: "Sofani Mesfun"
date: "9/23/2022"
output: html_document
---

In this project you will be working with Python.

1. *Knit* the empty file (to make sure everything is working)
2. Consistently *knit* the file each time you answer a question

⚠️ Students enrolled in CAP4755 should only solve: **1 to 6**

## Python Basics 

1. Compute the difference between 2022 and the year you started programming 
divide this by the difference between 2022 and the year you were born. 
Multiply this with 100 to get the percentage of your life you have been programming

```{python}
#Code here
from datetime import date
#Code here
yearStartedProg = 2017
yearBorn = 1991
todays_date = date.today()

perProgLife = ((todays_date.year - yearStartedProg) / (todays_date.year - yearBorn) ) * 100
print("The percentage of my life I have been programming = ", perProgLife , "%")
```



2. Compute the mean of the square root of a vector of 100 random numbers. What happens?

```{python}
#Code here
import numpy as np
vector_size = 100
vectorOfRandomNums = np.random.random(vector_size)
meanSquareRoot = np.mean(np.sqrt(vectorOfRandomNums))
meansquareRootAbs = np.mean(np.abs(np.sqrt(vectorOfRandomNums)))

meanSquareRoot
#using abs
meansquareRootAbs

```


3. Make a vector from 1 to 100. Make a for-loop which runs through the whole vector. Multiply the elements which are smaller than 11 or larger than 90 with 10 and the other elements with 0.1

```{python}
#Code here
for k in range(1,100): 
  if (k < 11) or (k > 90):
    print(k * 10);
  else:
     print(round((k * 0.1), 2));
```


4. Write a function for the previous ToDo, so  that you can feed it any vector you like  (as argument). You may use a for-loop in the function to do the computation with each element. 

```{python}
#Code here
vector01 = [1, 2, 3];
vector02 = [12, 7, 98];
vector03 = []
def myfun(anyVector):
  if ((len(anyVector) != 0)):
    for k in anyVector:
      if (k < 11) or (k > 90):
        print(k * 10);
      else:
        print(round((k * 0.1), 2));
  else:
    print ("length is zero");
myfun(vector01)
myfun(vector02)
myfun(vector03)

```


## Data Analysis

5. Pick a data from [this link](https://vincentarelbundock.github.io/Rdatasets/articles/data.html) and Read the data in Python

```{python}
#Code here
import pandas as pd
ChinaIncome = pd.read_csv("ChinaIncome.csv")
ChinaIncome
```



6. Plot histogram of the output/response variable

```{python}
#Code here
import matplotlib.pyplot as plt
import pandas as pd
df_ChinaIncome = pd.DataFrame(ChinaIncome)
Agriculture = df_ChinaIncome["agriculture"]
Commerce = df_ChinaIncome["commerce"] 
bins =[80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 250, 300,350, 400, 450,500, 550, 600, 700]

plt.style.use("fivethirtyeight")
plt.figure();
plt.title("China Income")
plt.xlabel("Sectors")
plt.ylabel("Income")
plt.tight_layout()
plt.hist([Agriculture, Commerce], bins =bins, edgecolor="black", rwidth=0.9,color=['red', 'blue'], label=['Agriculture', 'Commerce'])
plt.legend(loc='upper right')
plt.show()
plt.close()

```



7. Split data to 25% training and 75% testing data sets

```{python}
#Code here
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_percentage_error

#Splitting affairs data into 75% and 25% 
training_data, testing_data = train_test_split(df_ChinaIncome, test_size=0.75, random_state=20)
#75 % testing data 
testing_data
#25% Training data
training_data

```

8. fit a linear regression on training data set (see notes from class)

```{python}
#Code here
from sklearn import linear_model

# Create X and Y from training
Y = training_data["agriculture"] # response variable / outcome
X = training_data.drop(columns=["agriculture"]) #predictors / features

reg =  linear_model.LinearRegression().fit(X,Y)
```


9. Predict using the fit and testing data set
```{python}
#Code here
Y_test = testing_data["agriculture"]
X_test = testing_data.drop(columns=["agriculture"])
agriculture_y_pred = reg.predict(X_test) 
print(reg.coef_)
```

10. Calculate MAPE

```{python}
#Code here
mean_absolute_percentage_error(y_true=Y_test, y_pred=agriculture_y_pred)
```


